[package]
name = "seshat_schemas"
version = "0.1.0"
edition = "2021"

[lib]
name = "seshat_schemas"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.166", features = ["derive"] }